name: Playwright Tests
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
jobs:
    test:
      name: Run playwright tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Setup node.js ver
          uses: actions/setup-node@v4
          with:
            node-version: '24.13.1'
            cache: 'npm'
        - name: check node.js ver
          run: node --version
        - name: install dependencies
          run: npm ci
        - name: install playwright browsers
          run: npx playwright install --with-deps chromium
        - name: run playwright tests
          run: npx playwright test --headed=false
        - name: upload test results
          if: always()
          uses: actions/upload-artifact@v4
          with: 
            name: playwright-report
            path: |
              playwright-report/
              test-results/
              test-artifacts/
            retention-days: 30